### ISSUE TITLE
issue with BoxDecoration function

### ISSUE THREAD

**Issue by pythonAeny** [robertodevs/flutter_ecommerce_template#1]
![Untitled](https://user-images.githubusercontent.com/41165805/82763027-2bd9eb80-9e22-11ea-8bca-358c56ef9779.png)

Compiler message:
lib/screens/auth/confirm_otp_page.dart:180:47: Error: The argument type 'BoxDecoration Function(Color)' can't be assigned to the parameter type 'BoxDecoration Function(Color, Color, {double borderWidth, double radius})'.
 - 'BoxDecoration' is from 'package:flutter/src/painting/box_decoration.dart' ('/E:/flutter/packages/flutter/lib/src/painting/box_decoration.dart').
 - 'Color' is from 'dart:ui'.
                            pinBoxDecoration: (color) {
                                              ^
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^

Compiler message:
lib/screens/auth/confirm_otp_page.dart:180:47: Error: The argument type 'BoxDecoration Function(Color)' can't be assigned to the parameter type 'BoxDecoration Function(Color, Color, {double borderWidth, double radius})'.
 - 'BoxDecoration' is from 'package:flutter/src/painting/box_decoration.dart' ('/E:/flutter/packages/flutter/lib/src/painting/box_decoration.dart').
 - 'Color' is from 'dart:ui'.
                            pinBoxDecoration: (color) {
                                              ^
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture_stream.dart:92:3: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  PictureStream();
  ^^^^^^^^^^^^^
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.14.4/lib/src/picture_stream.dart:192:16: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
abstract class PictureStreamCompleter extends Diagnosticable {
               ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by robertodevs** [comment]
Thanks for your review, I have solved it by the last commit. I update some plugins and migrate to AndroidX the template.
