### ISSUE TITLE
Not working with Flutter 2.0

### ISSUE THREAD

**Issue by raihanameen** [robertodevs/flutter_ecommerce_template#10]
Lot of Widgets are deprecated in flutter 2.0

**Comment by ignertic** [comment]
@raihanameen I'm sure this is fixable, I'd like to use this template as well so how about we work on it together and open a PR here. I'm sure the authors would love that

**Comment by raihanameen** [comment]
> @raihanameen I'm sure this is fixable, I'd like to use this template as well so how about we work on it together and open a PR here. I'm sure the authors would love that

I've tried it last week, but I was not able to fix. Do you have any Idea about it?

**Comment by mohvic78** [comment]
I update  copy of it and it runs now  in flutter 2.0

**Comment by raihanameen** [comment]
> I update copy of it and it runs now in flutter 2.0

I just tried running the application which you have updated, but The error still exists.
I also checked all the other branches but still not running.

**Comment by alikhabazian** [comment]
> > I update copy of it and it runs now in flutter 2.0
> 
> I just tried running the application which you have updated, but The error still exists.
> I also checked all the other branches but still not running.

Can you solve the problem?

**Comment by alikhabazian** [comment]
> I update copy of it and it runs now in flutter 2.0

this code doesn't work at start

1. First I use @mohvic78 code
2. after that I have 2 error again 
    The method 'ancestorStateOfType' isn't defined for the class 'BuildContext'.
solve in
https://github.com/fluttercommunity/flutter_google_places/issues/140#issuecomment-786127985
and
    https://github.com/aloisdeniel/flutter_device_preview/issues/91#issuecomment-735256149
after that it work correct

**Comment by hanafiqp** [comment]
I too. Its not working on Flutter 2.0 :(

**Comment by hanafiqp** [comment]
> @raihanameen I'm sure this is fixable, I'd like to use this template as well so how about we work on it together and open a PR here. I'm sure the authors would love that

Noooo, its still  not runing for me. Even i am just 

> run pub get

**Comment by ozkanpakdil** [comment]
try https://github.com/alxkzmn/flutter_ecommerce_template/tree/flutter-2-fix it worked in my machine

**Comment by HoangHD123** [comment]
Fl

> thử https://github.com/alxkzmn/flutter_ecommerce_template/tree/flutter-2-fix nó đã hoạt động trong máy của tôi

How can you get it to run, can you give me the manual?

**Comment by HoangHD123** [comment]
I can't run because of error:
![image](https://user-images.githubusercontent.com/35024649/132134796-d036fe2f-5fce-491e-9ccd-729b2bd8f0cc.png)

**Comment by HoangHD123** [comment]
> try https://github.com/alxkzmn/flutter_ecommerce_template/tree/flutter-2-fix it worked in my machine

Thanks you ! I was able to run it <3
What did you fix in there to make it work, can you tell me ?

**Comment by robertodevs** [comment]
Ready guys, finally I am adding the flutter 2 migration to the master.
