### ISSUE TITLE
Step by step tutorial to run the templete in VS code

### ISSUE THREAD

**Issue by clerry** [robertodevs/flutter_ecommerce_template#8]
Hi Roberto, 

I encounter issue running your template in VS code. Would appreciate if you can do a video tutorial on how to use/run the template.

Thank you.

**Comment by HoangHD123** [comment]
I also can't run on android studio with flutter 2.2.3 and dart 2.13.4 can you help me to know why, thank you very much

**Comment by robertodevs** [comment]
Will try to create a youtube video to let you know how to run the template. Stay tuned. https://www.youtube.com/channel/UCoG6CM4OY3XYyZuGVjZZAOQ
